spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/just-test2
    username: postgres
    password: postgres
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/just-test2
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
